# Generated by Django 2.2.6 on 2019-11-01 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
