# Generated by Django 2.2.6 on 2019-10-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='post_date',
            field=models.DateTimeField(default=1),
        ),
    ]
