# Generated by Django 2.2.6 on 2019-11-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0002_recipe_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='we just need to do this'),
        ),
    ]
